components/Header.js
components/HeaderDropdownNav.js
components/dashboard/DashboardBlocks.js
components/dashboard/DashboardBlocksBlock.js
components/dashboard/DashboardTransactionsRow.js
components/utils/Moment.js
components/utils/Timer.js
package-lock.json
package.json

* Timers for Recent Blocks + Recent Transactions
* Switch between testnet dropdown options

Timers for Recent Blocks + Recent Transactions

---

backend/config/config.json
backend/loadDummyData.js
backend/models/index.js
backend/src/index.js

Refactored (simplified) read-only database setup for com.nearprotocol.explorer.select

---

backend/Dockerfile
backend/package-lock.json
backend/package.json
backend/src/index.js

/cc @ilblackdragon @robin-thomas

Implement real data fetching via Nearcore RPC

---

backend/src/index.js
frontend/components/dashboard/DashboardTransactionsRow.js

*Closes #36*
@robin-thomas The issue was in the DB saving routine (I used `blockInfo.hash` instead of `blockInfo.header.hash`... I should maintain caution when I write JS code, I am spoiled by Rust)

Fixed the 'invalid date' in transactions list

---

backend/src/index.js

@robin-thomas FYI, this and #45 PRs should improve the reliability of the backend.

Implemented proper error handling for WAMP RPC handler registrations

---

frontend/components/api/Details.js
frontend/components/dashboard/DashboardHeader.js

Display transactions per second (tps) and max tps

---

frontend/components/Transactions.js
frontend/components/api/Transactions.js
frontend/components/dashboard/DashboardTransactions.js
frontend/components/transactions/ActionMessage.js
frontend/components/transactions/ActionRow.js
frontend/components/utils/Balance.jsx

Fixes the messages in transcation actions

---

frontend/components/api/Details.js

*Resolve #11*
NOTE: It is a suboptimal solution

Show number of accounts/contracts

---

frontend/src/components/transactions/ActionMessage.jsx

Update action message typos and formatting

---

frontend/src/components/transactions/ActionMessage.tsx
frontend/src/components/transactions/ActionRow.tsx
frontend/src/components/transactions/__tests__/__snapshots__/ActionMessage.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ActionRow.test.tsx.snap
frontend/src/components/utils/AccountLink.tsx
frontend/src/components/utils/__tests__/AccountLink.test.tsx
frontend/src/components/utils/__tests__/__snapshots__/AccountLink.test.tsx.snap

Link account names (sender/receiver) to /accounts/<name> in list of transactions

---

backend/src/sync.js
frontend/src/components/accounts/AccountDetails.tsx
frontend/src/components/accounts/__tests__/AccountDetails.test.tsx
frontend/src/components/accounts/__tests__/__snapshots__/AccountDetails.test.tsx.snap
frontend/src/components/transactions/ReceiptRow.tsx
frontend/src/components/transactions/ReceiptsList.tsx
frontend/src/components/transactions/__tests__/__snapshots__/ReceiptRow.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ReceiptsList.test.tsx.snap
frontend/src/components/transactions/__tests__/common.tsx
frontend/src/libraries/explorer-wamp/accounts.ts
frontend/src/libraries/explorer-wamp/blocks.js
frontend/src/libraries/explorer-wamp/transactions.ts
frontend/src/pages/blocks/[hash].jsx
frontend/src/pages/transactions/[hash].jsx

Resolved the compatibility issues with nearcore 0.4

---

frontend/README.md
frontend/src/components/blocks/BlocksList.jsx
frontend/src/components/blocks/BlocksRow.jsx
frontend/src/components/dashboard/DashboardBlocks.jsx
frontend/src/components/dashboard/DashboardBlocksBlock.jsx
frontend/src/components/dashboard/DashboardHeader.jsx
frontend/src/components/dashboard/DashboardTransactions.jsx
frontend/src/components/nodes/Nodes.jsx
frontend/src/components/transactions/ActionsList.tsx
frontend/src/components/transactions/Transactions.tsx
frontend/src/components/transactions/TransactionsList.tsx
frontend/src/components/utils/Footer.jsx
frontend/src/libraries/explorer-wamp/transactions.ts
frontend/src/pages/index.jsx

Auto refresh

---

frontend/src/components/dashboard/DashboardHeader.jsx
frontend/src/libraries/explorer-wamp/blocks.js

Search by height

---

frontend/src/components/transactions/ActionRow.tsx
frontend/src/components/transactions/TransactionDetails.tsx
frontend/src/components/transactions/__tests__/__snapshots__/ActionRow.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ActionsList.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/TransactionDetails.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/TransactionsList.test.tsx.snap
frontend/src/components/transactions/__tests__/common.tsx
frontend/src/components/utils/ExecutionStatus.tsx
frontend/src/libraries/explorer-wamp/transactions.ts

Fixed a failed TX showing as completed

---

backend/models/Node.js
backend/src/wamp.js
frontend/src/components/nodes/NodeRow.jsx
frontend/src/components/nodes/Nodes.jsx
frontend/src/libraries/explorer-wamp/nodes.js
frontend/src/pages/api/nodes.js

write new handler to fetch telemetry data

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/transactions/Transactions.tsx
frontend/src/pages/accounts/[id].jsx
package-lock.json
package.json

Add loading

---

frontend/src/components/transactions/ReceiptRow.tsx
frontend/src/components/transactions/ReceiptsList.tsx
frontend/src/components/transactions/__tests__/ReceiptRow.test.tsx
frontend/src/components/transactions/__tests__/ReceiptsList.test.tsx
frontend/src/components/transactions/__tests__/common.tsx
frontend/src/libraries/explorer-wamp/transactions.ts
frontend/src/pages/accounts/[id].jsx
frontend/src/pages/transactions/[hash].jsx

The `receipts` field was renamed to `receipts_outcome`.

Fixed logs output

---

README.md
cli/README.md
cli/bin/near-explorer
cli/package-lock.json
cli/package.json
cli/src/commandQuery.js
cli/src/utils.js

It was a common request from many people on the team, so I extracted my local hacky script into a CLI tool.
**It is NOT meant for public use!**

feat: implemented a convenience tool to access NEAR Explorer Backend from command line

---

CODEOWNERS
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

@AnaisUrlichs Does this look right?

docs: added CODEOWNERS, CODE_OF_CONDUCT, and CONTRIBUTING documents

---

frontend/src/components/dashboard/DashboardHeader.jsx
frontend/src/components/utils/CardCell.tsx
frontend/src/pages/index.jsx

fix #180 
adding spinner when loading data on the dashboard
test with legal dashboard test

display spinner when loading

---

backend/models/Block.js
backend/src/index.js
backend/src/sync.js

@icerove I know that you are not very familiar with the backend, but it is still better to have a fresh look at the code, so I ask you to let me know if there is anything that catches your eye.
P.S. We still don't have any tests for the backend, so I just attest that it works on my laptop.

fix: Improved synchronization (backend) stability

---

CONTRIBUTING.md
README.md

add import order criterion in the contributing.md file

Import order criterion

---

frontend/src/components/transactions/ReceiptRow.tsx
frontend/src/components/transactions/ReceiptsList.tsx
frontend/src/components/transactions/__tests__/ReceiptRow.test.tsx
frontend/src/components/transactions/__tests__/__snapshots__/ReceiptRow.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ReceiptsList.test.tsx.snap
frontend/src/components/transactions/__tests__/common.tsx
frontend/src/libraries/explorer-wamp/transactions.ts

Fix 500 error

---

backend/models/Action.js
backend/models/Transaction.js
backend/src/sync.js
frontend/src/libraries/explorer-wamp/transactions.ts
frontend/src/pages/transactions/[hash].jsx

Actions table

---

backend/models/Block.js
backend/models/Transaction.js
backend/src/sync.js
frontend/src/components/transactions/TransactionDetails.tsx
frontend/src/components/transactions/__tests__/__snapshots__/TransactionDetails.test.tsx.snap
frontend/src/components/transactions/__tests__/common.tsx
frontend/src/components/utils/Gas.tsx
frontend/src/libraries/explorer-wamp/details.js
frontend/src/libraries/explorer-wamp/transactions.ts

feature: Improve performance by denormalizing and adding indecies to transactions DB table

---

frontend/src/libraries/explorer-wamp/details.js

feature: Avoid using JOINs to get stats for the Dashboard

---

frontend/src/components/utils/Footer.jsx
frontend/src/pages/_app.jsx

fix footer to bottom

---

backend/models/AccessKey.js
backend/src/sync.js

build access key table

---

frontend/src/components/dashboard/DashboardHeader.tsx
frontend/src/libraries/explorer-wamp/details.ts

fix 500 error when details api gives undefined and causes error

fix details api and ui

---

frontend/src/components/accounts/AccountRow.tsx
frontend/src/components/accounts/__tests__/AccountRow.test.js
frontend/src/components/accounts/__tests__/__snapshots__/AccountRow.test.js.snap

fix(frontend): Display balance + locked amount on the Accounts List page 

---

backend/src/sync.js
frontend/src/components/blocks/BlockDetails.tsx

fix(backend): Block #0 should be synced

---

frontend/src/components/dashboard/DashboardHeader.tsx
frontend/src/libraries/explorer-wamp/details.ts

As per our discussion today, we decided to remove TPS from the dashboard as it is not useful at the moment and confuses people. #265

feat(frontend): Replaced TPS with TXs (total number of transactions)

---

frontend/src/components/contracts/ContractDetails.tsx
frontend/src/libraries/explorer-wamp/contracts.ts

fix(frontend): Contracts from genesis should be shown

---

backend/src/sync.js

give genesis height as final fetching block

---

backend/Dockerfile
backend/models/index.js
backend/package-lock.json
backend/package.json
backend/src/sync.js
cli/src/commandQuery.js

* Ignore duplicate records, so it does not throw useless exceptions
* Auto-shutdown when genesis height is changed
* Auto-recover the dead backend instances (essentially patches the recent
betanet downtimes and combining with the auto-shutdown we get an
auto-restart feature for free)
* The error message for the missing chunk is now useful
Test Plan
=========
* Manually tested that the duplicate records during blocks sync and
genesis sync do not throw exceptions
* Manually tested that the backend shuts down automatically when the
genesis is different from the last one we observed during the genesis
sync
* Manually tested that runit supervisor auto-recovers the backend
instances when they are killed
* Manually confirmed that the error messages are not spammy

feat(backend): Improved the synchronization process

---

backend/src/wamp.js
frontend/src/pages/api/status.js

#315 
I tested manually the wamp endpoint and GET/api/status they all worked fine.

feat: Implemented health-check monitoring endpoints

---

backend/src/sync.js

devnet resets itself keeping the genesis height at 0, so we have to use another indicator, and it seems that genesis time gets actually updated on devnet resets.

feat(backend): Reset backend DB on genesis time change in addition to genesis height

---

frontend/src/components/blocks/BlocksRow.tsx
frontend/src/components/blocks/__tests__/BlocksRow.test.tsx
frontend/src/components/blocks/__tests__/__snapshots__/BlocksRow.test.tsx.snap

fix(frontend): Show Finalizing status in block list page

---

backend/models/index.js
backend/src/config.js
backend/src/index.js
backend/src/sync.js

This will be used on production for devnet since we do heavy load there and that produces 5GB database file every day.

feat(backend): Added a new feature to disable automatic backups on network reset to avoid spending too much disk space

---

backend/models/Block.js
backend/src/sync.js

Add backend implementation for #303

feat(backend): Save block author

---

frontend/src/components/transactions/ActionRowBlock.tsx
frontend/src/components/transactions/TransactionDetails.tsx

fix(frontend): Remove "/Finalized" from TX status

---

frontend/src/components/accounts/__tests__/__snapshots__/AccountDetails.test.tsx.snap
frontend/src/components/blocks/__tests__/__snapshots__/BlockDetails.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/TransactionDetails.test.tsx.snap
frontend/src/components/utils/CardCell.tsx

fix(front): Give column proper border line

---

backend/src/wamp.js

add method to pass test and pr

feat(backend): exposed `nearcore-validators` RPC API via WAMP

---

backend/src/wamp.js
frontend/cypress/integration/nodepage.spec.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/dashboard/DashboardHeader.tsx
frontend/src/components/nodes/NodeRow.tsx
frontend/src/components/nodes/__test__/NodeRow.test.tsx
frontend/src/components/nodes/__test__/__snapshots__/NodeRow.test.tsx.snap
frontend/src/components/utils/RpcProvider.tsx
frontend/src/libraries/explorer-wamp/blocks.ts
frontend/src/libraries/explorer-wamp/nodes.ts
frontend/src/pages/_app.jsx

feat(frontend): display stake of the validation nodes

---

frontend/src/components/blocks/BlockDetails.tsx
frontend/src/components/blocks/__tests__/BlockDetails.test.tsx
frontend/src/components/blocks/__tests__/BlocksRow.test.tsx
frontend/src/components/blocks/__tests__/__snapshots__/BlockDetails.test.tsx.snap
frontend/src/components/dashboard/__tests__/BlockBlock.test.tsx
frontend/src/libraries/explorer-wamp/blocks.ts

fix(frontend): Gas Used on Block Detail Page

---

frontend/src/components/utils/ListHandler.tsx

fix the issue for https://explorer.betanet.near.org/accounts/paulainsley1betanet.stakehouse.betanet as @jimmy3dita concerned in slack

fix(frontend)/scroll pagination hasMore issue while time out fetching

---

frontend/src/components/dashboard/DashboardBlocks.tsx
frontend/src/components/dashboard/DashboardTransactions.tsx
frontend/src/components/utils/ListHandler.tsx

fix #381 
fix the component not scroll anymore but still have animation

fix(frontend): Disable pagination on dashboard

---

frontend/src/libraries/explorer-wamp/transactions.ts
frontend/src/pages/accounts/[id].jsx

fix transaction sql query

---

backend/src/index.js
frontend/src/context/DatabaseProvider.jsx
frontend/src/context/ListProvider.jsx
frontend/src/context/NodeProvider.jsx
frontend/src/context/NodeStatsProvider.jsx

I find current one has some issues, let's revert unsubscribe part and I will create new PR for this.

fix unsubscribe issue 

---

backend/package-lock.json
backend/package.json
backend/src/config.js
backend/src/db-utils.js
backend/src/index.js
backend/src/sync.js
backend/src/utils.js
docker-compose.yml

feat(backend): Migrate away from EXPERIMENTAL_genesis_records RPC API to raw genesis.json file

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
backend/package.json
cli/package.json
frontend/package.json
frontend/src/components/accounts/AccountDetails.tsx
frontend/src/components/blocks/BlockDetails.tsx
frontend/src/components/contracts/ContractDetails.tsx
frontend/src/components/dashboard/DashboardHeader.tsx
frontend/src/components/transactions/TransactionDetails.tsx
frontend/src/components/utils/Header.jsx
frontend/src/components/utils/__tests__/Term.test.tsx

Migrate from nearprotocol.com to near.org links

---

frontend/src/components/transactions/__tests__/__snapshots__/ActionMessage.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ActionRow.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ActionsList.test.tsx.snap
frontend/src/components/utils/CodePreview.tsx

five new font for code

---

backend/src/index.js

fix the type error for genesis height

fix(backend): fix type error matching the genesis height

---

frontend/src/components/utils/Phase2Vote.jsx

fix the overflow

---

frontend/src/components/transactions/__tests__/__snapshots__/TransactionDetails.test.tsx.snap
frontend/src/components/utils/Gas.tsx

change gas display

---

frontend/src/components/utils/Gas.tsx

fix(frontend): Fixed teragas conversion

---

backend/src/config.js
frontend/src/components/utils/Phase2Vote.jsx
frontend/src/pages/index.jsx

fix #430
shorten time for loading from backend
only real the vote bar for mainnet

feat(frontend): Improved Clarity of Phase II Vote Progress Bar

---

frontend/src/components/accounts/AccountRow.tsx
frontend/src/components/accounts/__tests__/AccountRow.test.js
frontend/src/components/accounts/__tests__/__snapshots__/AccountRow.test.js.snap
frontend/src/components/transactions/ActionMessage.tsx
frontend/src/components/transactions/__tests__/__snapshots__/ActionMessage.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ActionRow.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ActionsList.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/TransactionDetails.test.tsx.snap
frontend/src/components/utils/AccountLink.tsx
frontend/src/components/utils/ListHandler.tsx
frontend/src/components/utils/__tests__/AccountLink.test.tsx
frontend/src/components/utils/__tests__/__snapshots__/AccountLink.test.tsx.snap

feat(frontend): shorten displayed long name

---

frontend/src/components/utils/Phase2Vote.jsx

add accurate number to vote bar since the bar length is longer and can included

add accurate number

---

backend/src/wamp.js
frontend/src/libraries/explorer-wamp/accounts.ts
frontend/src/libraries/explorer-wamp/contracts.ts

update query since we have new format

update query function wamp

---

frontend/src/components/transactions/ActionMessage.tsx
frontend/src/components/transactions/__tests__/ActionMessage.test.tsx
frontend/src/components/transactions/__tests__/__snapshots__/ActionMessage.test.tsx.snap

feat(frontend): Minor adjustments to how addition of keys is displayed

---

.github/workflows/codeql-analysis.yml

These automation tools may help to catch obvious things like unused variables which may indicate potentials bugs due to copy-paste or just typos.

ci: Introduce CodeQL for code quality reviews on PR

---

frontend/src/components/utils/Footer.jsx
frontend/src/components/utils/Header.jsx

feat(frontend): Replace "Contact Us" with "Join the community"

---

backend/config/database.js
backend/src/db-utils.js
backend/src/index.js

feat(backend): Configure the backend to use Indexer for Explorer database

---

frontend/src/components/accounts/AccountRow.tsx

Old: https://explorer.mainnet.near.org/accounts
New: https://near-explorer-frontend-pr-460.onrender.com/accounts

fix(frontend): Display the total balance of the account on the Accounts List page

---

backend/src/db-utils.js
backend/src/wamp.js

While working on #477, I hit a few discrepancies with the Indexer support on the backend.

fix(backend): Aligned the indexer support on the backend to produce the same events as the legacy-sync backend

---

frontend/src/context/ListProvider.jsx

fix the actions kind which consist with indexer and legacy

fix the kind undefined

---

frontend/src/libraries/explorer-wamp/accounts.ts
frontend/src/libraries/explorer-wamp/transactions.ts

*Resolves #212*
This will finally expose 2FA, lockup calls, and "hidden" transfers all of which are executed through cross-contract calls and thus only observable through receipts.
NOTE: This is only available with the Indexer backend!

feat(frontend): Exposed the account transactions that are touched in cross-contract calls (indexer-only!)

---

frontend/src/components/stats/ActiveAccountsByDate.tsx
frontend/src/components/stats/ActiveAccountsList.tsx
frontend/src/components/stats/ActiveContractsByDate.tsx
frontend/src/components/stats/ActiveContractsList.tsx
frontend/src/components/stats/GasUsedByDate.tsx
frontend/src/components/stats/NewAccountsByDate.tsx
frontend/src/components/stats/NewContractsByDate.tsx
frontend/src/components/stats/StakingBar.tsx
frontend/src/components/stats/TransactionsByDate.tsx
frontend/src/context/NodeProvider.jsx
frontend/src/pages/stats/index.jsx

Add total stake and stake bar chart to the stats page
add tooltip for bar chart
fix the date showing

Add staking volume

---

frontend/src/components/accounts/AccountDetails.tsx
frontend/src/components/accounts/__tests__/AccountDetails.test.tsx
frontend/src/components/accounts/__tests__/__snapshots__/AccountDetails.test.tsx.snap
frontend/src/libraries/explorer-wamp/accounts.ts

*Resolves #519* and also fixes the creation date for accounts created in genesis

fix: Fixed invalid deletion timestamp and genesis creation indicator

---

backend/src/db-utils.js
backend/src/index.js
backend/src/stats.js
backend/src/wamp.js
frontend/src/libraries/explorer-wamp/stats.ts
frontend/src/pages/api/stats/total-deposit-amount.js

Aggregate Deposit from Actions within Transactions

---

frontend/src/components/utils/TransactionCharts.jsx

fix the issue that transaction charts min value is not displayed as expected

fix the issue for transaction charts 

---

frontend/cypress/integration/dashboard.spec.js
frontend/src/components/dashboard/DashboardBlock.tsx

test: Add tests for the main dashboard page

---

frontend/public/static/images/icon-stats.svg
frontend/src/components/utils/HeaderNavDropdown.jsx
frontend/src/components/utils/MobileHeaderNavDropdown.jsx

Resolves #558 
@corwinharrell May I ask for a better icon and bikeshed the menu name?

feat(frontend): Added 'Charts & Stats' menu item

---

backend/src/db-utils.js

feat(backend): smooth out last day on stats

---

backend/src/db-utils.js

fix(backend): Fixed daily amount of transactions query 

---

backend/src/db-utils.js
backend/src/wamp.js

Change appi request for transaction details to use experimental data.

fix(frontend): Fix request to transaction details

---

frontend/src/components/stats/StakingBar.tsx

Fix typo in user-visible string

---

frontend/src/components/stats/ActiveAccountsByDate.tsx
frontend/src/components/stats/GasUsedByDate.tsx
frontend/src/components/stats/NewAccountsByDate.tsx
frontend/src/components/stats/NewContractsByDate.tsx
frontend/src/context/DatabaseProvider.tsx
frontend/src/libraries/explorer-wamp/stats.ts

1. fix #586 live accounts charts 
2. fix #568 unique contracts charts
3. active account count by week
4. gas fee burnt over time ( part of #548)

frontend/deploy new charts  

---

backend/src/db-utils.js
backend/src/wamp.js

the query is for bridge tracking :
for each token, who is mint and hold this token

feat(backend): exposed a method to query token holders of bridge contracts

---

frontend/src/components/stats/ActiveAccountsByDate.tsx
frontend/src/components/stats/ActiveContractsByDate.tsx
frontend/src/components/stats/NewAccountsByDate.tsx
frontend/src/components/stats/NewContractsByDate.tsx
frontend/src/components/stats/TransactionsByDate.tsx

feat(frontend): Update charts titles on stats page

---

frontend/src/components/contracts/ContractDetails.tsx

Resolves https://github.com/near/near-explorer/issues/605#issuecomment-821007353
Is it better now?

docs: Improved help message about locked contract

---

frontend/src/components/utils/HeaderNetworkDropdown.jsx

Color network icon in options must not depend on current network

---

frontend/src/components/transactions/ReceiptRow.tsx
frontend/src/components/transactions/__tests__/__snapshots__/ReceiptRow.test.tsx.snap

feat(frontend): Display full receipt id on the Transaction Details page for convenience

---

frontend/src/components/utils/ListHandler.tsx

fix(frontend): Transaction list is always loading when search at second time

---

backend/src/db-utils.js

fix(backend): Current week should not be counted for weekly Active Accounts

---

backend/src/db-utils.js

This fixes a regression I introduced in #615

fix(backend): Current day should not be counted for daily stats

---

frontend/src/libraries/explorer-wamp/contracts.ts

fix(frontend): Fix contract details displaying

---

backend/src/index.js
backend/src/near.js
backend/src/stats.js
backend/src/wamp.js
frontend/src/components/nodes/NearBadge.tsx
frontend/src/components/nodes/NodesCard.tsx
frontend/src/components/stats/ProtocolConfigInfo.tsx
frontend/src/components/utils/Balance.jsx
frontend/src/components/utils/InfoCard.tsx
frontend/src/context/NetworkStatsProvider.tsx
frontend/src/libraries/explorer-wamp/stats.ts
frontend/src/pages/stats/index.jsx

feat(frontend): expose protocol configuration on stats page

---

frontend/cypress/integration/accounts-list-page.spec.js
frontend/cypress/integration/blocks-list-page.spec.js
frontend/cypress/integration/dashboard-page.spec.js
frontend/cypress/integration/dashboard-search.spec.js
frontend/cypress/integration/nodes-page.spec.js
frontend/cypress/integration/transactions-page.spec.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/blocks/BlockDetails.tsx
frontend/src/components/blocks/BlocksRow.tsx
frontend/src/components/transactions/TransactionAction.tsx
frontend/src/components/transactions/TransactionDetails.tsx
frontend/src/context/DatabaseProvider.tsx

fix(frontend): Fix transaction details status

---

frontend/src/components/stats/ProtocolConfigInfo.tsx

fix(frontend): Fix live account count on Stats page

---

backend/src/aggregations.js
backend/src/config.js
backend/src/db-utils.js
backend/src/index.js
backend/src/wamp.js
frontend/src/libraries/explorer-wamp/details.ts

feat(backend): Calculate circulating supply

---

frontend/src/components/transactions/ActionMessage.tsx

fix(frontend): Endless 'Loading...' when arguments are empty

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/utils/Search.jsx
frontend/src/libraries/explorer-wamp/accounts.ts
frontend/src/libraries/explorer-wamp/contracts.ts

fix(frontend): Fix searching for deleted users

---

frontend/src/components/nodes/ValidatorRow.tsx
frontend/src/components/nodes/__test__/__snapshots__/ValidatorRow.test.tsx.snap
frontend/src/components/nodes/__test__/__snapshots__/ValidatorsList.test.tsx.snap
frontend/src/components/transactions/ReceiptRow.tsx
frontend/src/components/transactions/__tests__/__snapshots__/ReceiptRow.test.tsx.snap

Partially resolves #646 
It resolves such points 1 and 2.

fix(frontend): Fix confusing information on Nodes page

---

backend/src/stats.js

It was reported that New Accounts chart is missing and after some investigation, I realized that it is due to the fact that the database replica we use can sometimes return errors on long-running queries. Retrying the query usually helps, so I went ahead implementing this `retriable` decorator.
*P.S. The diff contains tons of whitespace changes, so use the Github feature to hide whitespace changes when reading the diff*

fix(backend): auto-retry aggregating stats on failure

---

backend/src/aggregations.js
backend/src/index.js
frontend/src/pages/api/circulating-supply-in-near.js
frontend/src/pages/api/circulating-supply.js

We need that for #636
Recreated the PR because it's not possible to change src/dst after creating
The base is not master, it's the branch for #636

feat(backend): add transition logic for circulating supply

---

frontend/README.md
frontend/cypress/fixtures/mixedcase-account-ids.json
frontend/cypress/integration/accounts-list-page.spec.js
frontend/cypress/integration/blocks-list-page.spec.js
frontend/cypress/integration/dashboard-search.spec.js
frontend/cypress/integration/transactions-page.spec.js
frontend/package-lock.json
frontend/package.json

fix(frontend): Fix failing e2e tests

---

frontend/package-lock.json
frontend/src/components/accounts/AccountDetails.tsx
frontend/src/components/accounts/__tests__/AccountDetails.test.js
frontend/src/components/accounts/__tests__/__snapshots__/AccountDetails.test.js.snap
frontend/src/components/transactions/TransactionDetails.tsx
frontend/src/components/transactions/__tests__/__snapshots__/ActionRow.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ActionsList.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ReceiptRow.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/TransactionDetails.test.tsx.snap
frontend/src/libraries/explorer-wamp/accounts.ts
package-lock.json

Fix loading transactions on heavy accounts

---

backend/src/db-utils.js
frontend/src/pages/api/fees-of-previous-7-days-utc.js
frontend/src/pages/api/fees-of-previous-day-utc.js

feat(frontend): Implement v2 of API endpoint to view fees

---

frontend/src/components/utils/Header.jsx
frontend/src/libraries/language.js
frontend/src/libraries/moment.js
frontend/src/translations/vi.global.json

Contribution to the bounty: https://github.com/near/bounties/issues/62

feat(frontend): NEAR Explorer translation for Vietnamese Users

---

frontend/src/components/accounts/__tests__/__snapshots__/AccountDetails.test.js.snap
frontend/src/components/nodes/NodesCard.tsx
frontend/src/components/nodes/__test__/__snapshots__/ValidatorRow.test.tsx.snap
frontend/src/components/nodes/__test__/__snapshots__/ValidatorsList.test.tsx.snap
frontend/src/components/stats/ProtocolConfigInfo.tsx
frontend/src/components/transactions/__tests__/__snapshots__/ActionMessage.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ReceiptRow.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/TransactionDetails.test.tsx.snap
frontend/src/components/utils/Balance.jsx
frontend/src/pages/nodes/validators.jsx

Fix near ballance on stats page

---

frontend/src/components/nodes/ValidatorMetadataRow.tsx
frontend/src/translations/zh-hans.global.json

* Fix #710 : missing Chinese translation on Nodes page
* node website href unavailable

fix(frontend): missing Chinese translation on Nodes page and website href unavailable

---

backend/Dockerfile
frontend/Dockerfile

refactor: Upgraded Node.js in Docker images to 16.4.2

---

frontend/src/components/utils/MobileHeaderNavDropdown.jsx

> On mobile browser: both chrome and embedded on mobile the menu button doesn’t work. Does anyone else has the same?

fix(frontend): Fix mobile menu expanding

---

frontend/src/components/accounts/AccountDetails.tsx
frontend/src/components/nodes/CumulativeStakeChart.tsx
frontend/src/components/nodes/ValidatorMainRow.tsx
frontend/src/components/nodes/ValidatorRow.tsx
frontend/src/components/nodes/ValidatorTelemetryRow.tsx
frontend/src/components/nodes/__test__/__snapshots__/ValidatorRow.test.tsx.snap
frontend/src/components/nodes/__test__/__snapshots__/ValidatorsList.test.tsx.snap

Resolve issue when "0" is shown

fix(frontend): Fix condition of TelemetryRow appearance

---

backend/src/db-utils.js
backend/src/index.js
backend/src/stats.js
backend/src/wamp.js
frontend/src/components/stats/CirculatingSupplyStats.tsx
frontend/src/components/stats/TransactionsByDate.tsx
frontend/src/components/utils/Header.jsx
frontend/src/libraries/explorer-wamp/stats.ts
frontend/src/pages/stats/index.jsx
frontend/src/translations/en.global.json

feat(frontend): Display circulating supply on stats page

---

backend/src/index.js

refactor(backend): Catch error when connect to telemetry db failed

---

backend/src/accounts.js
backend/src/db-utils.js
backend/src/wamp.js

test(backend): Introduce method for account activity

---

backend/src/chunks.js
backend/src/db-utils.js

Resolves https://github.com/near/near-indexer-for-explorer/issues/201

fix(backend): Fix query for gasUsed in block

---

backend/package-lock.json
backend/package.json
backend/src/near.js
frontend/package-lock.json
frontend/package.json

feat(backend): Update `seat_price` algorithm

---

frontend/jest.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/accounts/__tests__/__snapshots__/AccountDetails.test.js.snap
frontend/src/components/accounts/__tests__/__snapshots__/AccountRow.test.js.snap
frontend/src/components/blocks/__tests__/__snapshots__/BlockDetails.test.tsx.snap
frontend/src/components/blocks/__tests__/__snapshots__/BlocksRow.test.tsx.snap
frontend/src/components/nodes/__test__/__snapshots__/NodeRow.test.tsx.snap
frontend/src/components/nodes/__test__/__snapshots__/NodesEpoch.test.tsx.snap
frontend/src/components/nodes/__test__/__snapshots__/ValidatorRow.test.tsx.snap
frontend/src/components/nodes/__test__/__snapshots__/ValidatorsList.test.tsx.snap
frontend/src/components/transactions/ActionIcons.tsx
frontend/src/components/transactions/__tests__/__snapshots__/ActionMessage.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ActionRow.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ActionsList.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ReceiptRow.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/TransactionDetails.test.tsx.snap
frontend/src/components/utils/__tests__/__snapshots__/AccountLink.test.tsx.snap
frontend/src/components/utils/__tests__/__snapshots__/CardCell.test.tsx.snap
frontend/src/components/utils/__tests__/__snapshots__/ReceiptLink.test.tsx.snap
frontend/src/components/utils/__tests__/__snapshots__/Term.test.tsx.snap

As I [mentioned before](https://github.com/near/near-explorer/pull/814#issuecomment-993471495) DX became a little worse (extra attributes you can't remove atm without writing rust add-on & no svg snapshot), but now we're working on Rust compilation!

refactor(frontend): Next.js-generated jest config

---

backend/src/near.js

refactor(backend): Refactor logic of validators staking status

---

backend/src/db-utils.js

refactor(backend): Display latest telemetry information for validator

---

frontend/package-lock.json
frontend/package.json
frontend/src/libraries/wdyr.ts
frontend/src/pages/_app.tsx

The `why-did-you-render` is a very helpful tool to have to debug unnecessary rerenders.

Feature (frontend): Why did you render

---

frontend/src/components/utils/Footer.tsx
frontend/src/components/utils/HeaderNetworkDropdown.tsx
frontend/src/components/utils/Link.tsx
frontend/src/components/utils/Search.tsx
frontend/src/components/utils/Term.tsx
frontend/src/components/utils/WalletLink.tsx
frontend/src/hooks/analytics/use-analytics-init.ts
frontend/src/hooks/analytics/use-analytics-track-on-mount.ts
frontend/src/hooks/analytics/use-analytics-track.ts
frontend/src/pages/_app.tsx
frontend/src/pages/accounts/[id].tsx
frontend/src/pages/accounts/index.tsx
frontend/src/pages/blocks/[hash].tsx
frontend/src/pages/blocks/index.tsx
frontend/src/pages/index.tsx
frontend/src/pages/nodes/online-nodes.tsx
frontend/src/pages/nodes/validators.tsx
frontend/src/pages/partner/index.tsx
frontend/src/pages/stats/index.tsx
frontend/src/pages/transactions/[hash].tsx
frontend/src/pages/transactions/index.tsx

Refactor (frontend): mixpanel as hook

---

frontend/cypress/integration/transactions-page.spec.ts
frontend/src/components/blocks/Blocks.tsx
frontend/src/components/transactions/Transactions.tsx

I didn't check [that](https://github.com/near/near-explorer/pull/829#issuecomment-998766979) comment properly, my bad!

Fix: FlipMove & no ref

---

frontend/cypress/integration/account-details-navigation.spec.ts
frontend/src/pages/_app.tsx
frontend/src/pages/accounts/[id].tsx
frontend/src/pages/blocks/[hash].tsx
frontend/src/pages/transactions/[hash].tsx

That's effectively a duplicate of https://github.com/near/near-explorer/pull/831
I merged it into `only-functional-components`, but eventually the branch is not changed at all.
Apparently, I don't get some things happening in GitHub.
Please let me know if you understand what happened.

Refactor (frontend): server-side props

---

frontend/Dockerfile
frontend/next.config.js
frontend/next.config.ts
frontend/nextjs.tsconfig.json
frontend/package.json
frontend/src/__mocks__/next/config.ts
frontend/src/context/NetworkContext.tsx
frontend/src/libraries/config.ts
frontend/src/libraries/explorer-wamp/index.ts
frontend/src/pages/_app.tsx
frontend/tsconfig.json

Fixing: https://github.com/near/near-explorer/issues/843

Docker image for front-end fix

---

frontend/src/pages/accounts/[id].tsx
frontend/src/pages/blocks/[hash].tsx
frontend/src/pages/transactions/[hash].tsx

Apparently, we broke serialization of errors in multiple pages leading to errors (at least in dev environment).

Fix: error pages serialization

---

frontend/src/components/transactions/Transactions.tsx
frontend/src/components/utils/ListHandler.tsx

Fixing https://github.com/near/near-explorer/issues/864

Fix: transaction list does not update on block / account change

---

frontend/src/pages/_app.tsx

fix(frontend): Dates in SSR are not rendered in user language

---

frontend/src/components/stats/GasUsedByDate.tsx

Resolves https://github.com/near/near-analytics/issues/41

fix: Fixed the chart of Daily Gas Fee with the values that are higher than 1000NEAR

---

frontend/next.config.ts

It was fixed pretty fast: https://github.com/webpack/webpack/pull/15266

Revert: Fix: ESM module import (#873)

---

frontend/src/pages/_app.tsx

A little bit of simplification for `NextApp` types.

Refactor: Simpler app types

---

frontend/package-lock.json
frontend/package.json

https://github.com/near/near-explorer/pull/888 was definitely not enough to update webpack automatically :)

Fix: nextjs webpack update

---

frontend/src/providers/blocks.ts

Resolving bug introduced by `bn.js`: https://github.com/indutny/bn.js/issues/186

Fix: Infinite loop on BN.js null instead of 0

---

backend/src/accounts.js
backend/src/db-utils.js
backend/src/receipts.js
backend/src/transactions.js
backend/src/wamp.js
frontend/src/components/receipts/ReceiptsExecutedInBlock.tsx
frontend/src/components/receipts/ReceiptsIncludedInBlock.tsx
frontend/src/components/receipts/ReceiptsList.tsx
frontend/src/libraries/wamp/types.ts
frontend/src/pages/blocks/[hash].tsx
frontend/src/translations/en/common.json
frontend/src/translations/ru/common.json
frontend/src/translations/vi/common.json
frontend/src/translations/zh-hans/common.json

Partially resolves: #851 
This PR is a part of disscussion of [another PR](https://github.com/near/near-explorer/pull/868)

feat(frontend): Expose all included and executed receipts in particular block

---

backend/src/near.js
frontend/src/components/nodes/ValidatorCollapsedRow.tsx
frontend/src/components/nodes/ValidatorRow.tsx
frontend/src/components/nodes/ValidatorTelemetryRow.tsx
frontend/src/components/nodes/__test__/validators.tsx
frontend/src/libraries/wamp/types.ts
frontend/src/translations/en/common.json
frontend/src/translations/ru/common.json
frontend/src/translations/vi/common.json
frontend/src/translations/zh-hans/common.json

feat(frontend): Display 'chunk produced / expected' on Nodes page

---

frontend/src/components/utils/ReceiptLink.tsx

No chlidren in ReceiptLink

---

backend/src/db-utils.ts
backend/src/index.ts
backend/src/stats.ts
backend/src/wamp.ts
frontend/src/libraries/wamp/types.ts

I hope to refactor everything later as it shouldn't be that many touched files for just one unused function, I believe.

Remove unused get-partner-unique-user-amount

---

frontend/src/components/utils/MobileHeaderNavDropdown.tsx

The types are actually pretty straight

No ambiguous types in Header on MouseEvent

---

.github/workflows/continuous-integration-workflow.yml

Probably it's time to upgrade :)

Proper node version in CI

---

frontend/src/components/accounts/AccountDetails.tsx

Fix the output of the income transaction count on the account page

---

backend/src/index.ts
backend/src/stats.ts
frontend/src/pages/api/circulating-supply-in-near.ts
frontend/src/pages/api/circulating-supply.ts
frontend/src/pages/api/fees-of-previous-7-days-utc.ts
frontend/src/pages/api/fees-of-previous-day-utc.ts
frontend/src/pages/api/metrics/indexer.ts
frontend/src/pages/api/nodes.ts

Logging gets in the way while debugging production, but doesn't provide meaningful information.
Let's get logging back when we get logging streams.

Feat: remove excessive logging

---

frontend/src/libraries/wamp/connection.ts

And a little bit of logging for frontend to keep us informed on BFF server

Feature: frontend wamp logging

---

frontend/src/libraries/wamp/connection.ts

The problem was that 'caching' system had race condition inside of it so we sent multiple subscription requests to wamp.
Apparently, wamp handled it gracefully, but the chances are it will fail if we migrate.

Fix: multiple subscriptions

---

backend/src/checks.ts
backend/src/config.ts
backend/src/db-utils.ts
backend/src/index.ts
backend/src/utils.ts
frontend/src/components/dashboard/DashboardTransaction.tsx
frontend/src/components/dashboard/DashboardTransactionsHistoryChart.tsx
frontend/src/hooks/subscriptions.ts
frontend/src/libraries/wamp/types.ts

I believe it's a easier-to-read and easier-to-tune version of regular checks on backend
The biggest problem of this PR is that it's going to be hard to blame code because most of it just moved.

Factoring out checks

---

frontend/src/pages/_app.tsx

We're going to have more context soon, let's have this change separate

App context

---

backend/src/procedure-handlers.ts
frontend/next.config.ts
frontend/src/components/utils/DeployInfo.tsx
frontend/src/pages/_app.tsx
frontend/src/types/procedures.ts

A small view to understand what commit is currently deployed and what backend are we fetching data from.

Feature: deploy info

---

backend/src/accounts.ts
backend/src/blocks.ts
backend/src/chunks.ts
backend/src/contracts.ts
backend/src/near.ts
backend/src/receipts.ts
backend/src/stats.ts
backend/src/transactions.ts
backend/src/utils.ts
frontend/src/components/utils/InfoCard.tsx
frontend/src/components/utils/Table.tsx

Migrating
```ts
function foo() {
// ...
}
// ...
export { foo };
```
to
```ts
export const foo = () => {
// ...
}
```

Refactor: remove distant export

---

frontend/src/hooks/use-query.ts
frontend/src/libraries/queries.ts
frontend/src/pages/_app.tsx
frontend/src/pages/accounts/[id].tsx
frontend/src/pages/blocks/[hash].tsx
frontend/src/pages/transactions/[hash].tsx

Refactor: react-query on SSR

---

backend/src/accounts.ts
backend/src/procedure-handlers.ts
common/src/types/procedures.ts
frontend/src/components/accounts/AccountDetails.tsx
frontend/src/components/accounts/AccountRow.tsx
frontend/src/components/accounts/__tests__/AccountDetails.test.tsx

A little bit of refactoring as I got confused a couple of times.
Also fixes bug of not showing deleted accounts.

Refactor: account details

---

frontend/additional.d.ts
frontend/package-lock.json
frontend/package.json
frontend/src/components/transactions/ActionMessage.tsx
frontend/src/components/transactions/__tests__/__snapshots__/ActionRow.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ActionsList.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ReceiptRow.test.tsx.snap
frontend/src/components/utils/CodePreview.tsx
frontend/src/components/utils/Expandable.tsx

In an attempt to migrate to npm workspaces (which is one of the workarounds to test out `trpc` library) I found out we have conflicting `react` version on `react-motion` library used by `react-text-collapse` library.
It took me way less time to write my own copy of this library than to figure out how to resolve the conflict.

Feature: expandable

---

frontend/src/components/transactions/ActionMessage.tsx
frontend/src/components/transactions/ActionRowBlock.tsx
frontend/src/components/transactions/__tests__/__snapshots__/ActionRow.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ActionsList.test.tsx.snap
frontend/src/components/transactions/__tests__/__snapshots__/ReceiptRow.test.tsx.snap
frontend/src/components/utils/CodePreview.tsx

Fixes https://github.com/near/near-explorer/issues/1001

Fix: code wrapper marksup

---

backend/.dockerignore
backend/Dockerfile
common/package.json
docker-compose.yml
frontend/.dockerignore
frontend/Dockerfile
frontend/next.config.ts
frontend/nextjs.tsconfig.json
frontend/package.json
package-lock.json

Fixes https://github.com/near/near-explorer/issues/1023

Fix: docker

---

frontend/Dockerfile

Current ENTRYPOINT doesn't work, but this fixes it

Fix error with frontend Dockerfile

---

backend/src/config.ts
backend/src/cron/index.ts
backend/src/cron/tasks.ts
backend/src/database/queries.ts
backend/src/providers/stats.ts
backend/src/router/procedures.ts
backend/src/router/subscriptions.ts
backend/src/router/types.ts
frontend/src/components/stats/CirculatingSupplyStats.tsx

We can significantly reduce amount of queries to the analytics database.
The only quirk here I see is timezones.
I'm not sure at what moment operate all the actors and we should update such statistics.

Refactor: tokens supply sub

---

backend/src/router/subscriptions.ts
common/src/types/trpc.ts
frontend/src/hooks/use-subscription.ts

Fixes: https://github.com/near/near-explorer/issues/1025

Feature: generic subscriptions helper

---

frontend/react.d.ts
frontend/src/components/beta/common/Tabs.tsx
frontend/src/hooks/use-account-page-options.ts
frontend/src/pages/beta/accounts/[...slug].tsx

Introducing tab links for the account in beta

Feature: account tabs links

---

backend/src/database/queries.ts
backend/src/providers/fungible-tokens.ts
backend/src/router/account.ts
backend/src/utils/near.ts
common/src/types/procedures.ts
frontend/src/components/beta/accounts/AccountFungibleTokenHistory.tsx
frontend/src/components/beta/accounts/AccountFungibleTokens.tsx
frontend/src/components/beta/accounts/AccountTabs.tsx
frontend/src/components/utils/Link.tsx
frontend/src/components/utils/TokenAmount.tsx
frontend/src/hooks/use-account-page-options.ts
frontend/src/libraries/formatting.ts
frontend/src/pages/beta/accounts/[...slug].tsx

There is no design here, but you can check out the data flow on page:
https://frontend-pr-969-kgmz.onrender.com/beta/accounts/v2.ref-finance.near
https://frontend-pr-969-kgmz.onrender.com/beta/accounts/vlad.near/fungible-tokens/kongztoken.near

Feature: fungible tokens on account

---

backend/src/cron/index.ts
backend/src/cron/tasks.ts
backend/src/database/queries.ts
backend/src/providers/stats.ts
backend/src/router/stats.ts
backend/src/router/subscriptions.ts
backend/src/router/types.ts
backend/src/utils/bigint.ts
common/src/utils/near.ts
frontend/src/components/stats/GasUsedByDate.tsx
frontend/src/components/stats/TransactionsByDate.tsx
frontend/src/libraries/bigint.ts
frontend/src/libraries/stats.ts

Carefully moving some stats to a more readable solution - aka subscriptions.

Refactor: gas used subscription

---

.github/actions/upload-frontend-stats/action.yml
.github/workflows/comment.md
.github/workflows/continuous-integration-workflow.yml
frontend/README.md
frontend/next.config.ts
frontend/package.json
package-lock.json

Fixes: https://github.com/near/near-explorer/issues/1041

Feature: bundle stats reporter

---

backend/src/router/account/fungible-tokens.ts
backend/src/router/fungible-tokens/index.ts
backend/src/router/index.ts
common/src/types/procedures.ts
frontend/src/pages/beta/fungible-tokens/index.tsx

We'll probably need it someday
Staging: https://frontend-pr-957-d14z.onrender.com/
FT list: https://frontend-pr-957-d14z.onrender.com/beta/fungible-tokens/

Feature: fungible tokens

---

backend/src/router/block/get-hash-by-id.ts

Fix search by block hash

---

backend/src/cron/tasks.ts
backend/src/database/databases.ts
backend/src/router/account/by-id.ts
backend/src/router/account/utils.ts
backend/src/router/contract/by-id.ts
frontend/src/components/accounts/AccountDetails.tsx
frontend/src/components/beta/accounts/AccountHeader.tsx
frontend/src/components/beta/accounts/AccountTabs.tsx
render.yaml

Shardnet doesn't have analytics DB, let's be prepared for it and not throw a bunch of errors into nowhere

Feature: optional analytics

---

frontend/src/components/utils/Search.tsx
frontend/src/hooks/use-query-param.ts
frontend/src/pages/index.tsx
frontend/tsconfig.json

As per original PR: https://github.com/near/near-explorer/pull/1090

The index page now supports an optional 'q' query string param for searching

---

backend/src/server.ts
backend/src/utils/html.ts

Seems like we don't log 500's on the backend side.

Feateure: backend fallback logging

---

frontend/Dockerfile

Similar to https://github.com/near/near-explorer/commit/194e474c095451be8fda237cee151b91c69c7851

Fix: dockerfile & node_modules on frontend

---

backend/src/index.ts
backend/src/server.ts

This should reduce amount of text on expected (and unexpected) errors on frontend.

TRPC error handling

---

backend/src/router/transaction/list.ts

@telezhnaya would be great if you can add details why this query is better than the old one.

Refactor: faster transactions list on account

---

backend/src/cron/tasks.ts

Data was migrated from `name.near` to new contract `pool-details.near` with new functionality https://github.com/zavodil/near-pool-details/commit/d36f6b7cdbd30f681d7e4c0ed26e7ec331b5e8a6

Update pool details contract  => pool-details.near

---

frontend/src/components/accounts/AccountDetails.tsx
frontend/src/components/accounts/AccountRow.tsx
frontend/src/components/beta/accounts/AccountFungibleTokenHistory.tsx
frontend/src/components/beta/transactions/TransactionHeader.tsx
frontend/src/components/blocks/BlockDetails.tsx
frontend/src/components/contracts/ContractDetails.tsx
frontend/src/components/transactions/TransactionDetails.tsx
frontend/src/components/utils/CopyToClipboard.tsx
frontend/src/libraries/styles.ts

Closes https://github.com/near/near-explorer/issues/997
@telezhnaya Please let me know if I forgot to add a button somewhere.

Feature: copy to clipboard timestamps

---

render.yaml

- They are currently suffering of memory starvation.

Increase Render instance types to standard

---

frontend/src/components/utils/Search.tsx

https://user-images.githubusercontent.com/74172766/220989104-0f406e20-d7d8-43d7-8b95-ab9c517b63c8.mov
https://user-images.githubusercontent.com/74172766/220989148-80c09494-2812-4529-b761-73fa61e963aa.mov

Fix: search text input caret behaviour

---

backend/src/router/utils/search.ts
frontend/src/components/utils/Search.tsx
frontend/src/pages/index.tsx

Fixes https://github.com/near/near-explorer/issues/1142
I'm not sure what this kind of request is - a mutation or a query, but changing it to mutation was the simplest way to solve the problem.
Also, added the loading indicator for the search.

Fix: Repeated search doesn't work

---

frontend/src/components/dashboard/DashboardBlock.tsx
frontend/src/components/dashboard/DashboardNode.tsx
frontend/src/components/dashboard/DashboardTransaction.tsx
frontend/src/components/utils/ListHandler.tsx
frontend/src/components/utils/LongCardCell.tsx
frontend/src/libraries/react.ts

Seems like we have a pattern here with cells..

Refactor: dashboard cells with subscriptions

---

frontend/src/components/beta/accounts/AccountNonFungibleTokens.tsx
frontend/src/components/utils/CopyToClipboard.tsx
frontend/src/components/utils/Search.tsx
frontend/src/components/utils/Term.tsx
frontend/src/hooks/use-query-param.ts

React 18 is being more strict than React 17, let's prepare to that in this commit.

Refactor: strict handler types

---

frontend/src/components/beta/accounts/AccountContract.tsx
frontend/src/components/beta/accounts/AccountHeader.tsx

Refactor: factor out account contract

---

frontend/src/components/utils/ErrorMessage.tsx

There is no sense to show error without any action

Refactor: mandatory onRetry

---

backend/src/router/account/by-id.ts

We already verify account id in zod refinement

Refactor: unneeded verification

---

frontend/public/static/images/icon-m-copy.svg
frontend/src/components/accounts/AccountDetails.tsx
frontend/src/components/accounts/__tests__/__snapshots__/AccountDetails.test.tsx.snap

Currently, a couple of "copy to clipboard" buttons don't actually let copy-paste data, replacing them with working ones.

Refactor: unified CopyToClipboard

---

.github/workflows/gcp-on-pr-closed.yml

- Tested the flow runs successfully on my branch

Fix the PR_NUMBER env var syntax

---

backend/src/utils/actions.ts
backend/src/utils/receipt-status.ts
common/src/types/rpc.ts

Some RPC types preps before we actually implement proper UI.

Feature: delegate action preparations

---

frontend/src/pages/_app.tsx

Examples:
https://pr-1182---explorer-frontend-vcqilefdcq-uc.a.run.app/beta/accounts/vlad.near?embedded=true
https://pr-1182---explorer-frontend-vcqilefdcq-uc.a.run.app/beta/transactions/3HMfXdv3sBapesmzZpcLsSjdsP2WCy8Um9U4BJ8wVuk2?embedded=true

Feature: embedded pages

---

frontend/src/components/utils/LanguageToggle.tsx
frontend/src/hooks/use-language.ts
frontend/src/libraries/language.ts
frontend/src/pages/_app.tsx
frontend/src/testing/utils.tsx

Forced language is needed in embedded pages (may have other use cases)

Feature: forced language

---

frontend/src/components/beta/transactions/TransactionHeader.tsx
frontend/src/context/SSRContext.tsx
frontend/src/hooks/use-date-format.ts
frontend/src/pages/_app.tsx

There's one more [mismatch](https://github.com/near/near-explorer/pull/1189) on SSR.

Fix: tz offset mismatch

---

backend/src/context.ts
backend/src/router/subscriptions.ts
backend/src/router/types.ts

Some types were extracted as well as typesafe `withTopic` function.

Refactor: subscriptions simplified

---

backend/src/index.ts
backend/src/server.ts

We need this for Sentry feature

Feature: TRPC resolve not 200 codes

---

frontend/next.config.ts

Add default security headers to frontend

---

frontend/package.json
frontend/src/components/blocks/Blocks.tsx
frontend/src/components/utils/ListHandler.tsx
package-lock.json

Seems like we can make a poor man's infinite scroll with just one hook.
Closes https://github.com/near/near-explorer/issues/296

Refactor: remove infinite scroll
