next.config.js
@robin-thomas As you have pointed out, there is no need in the TypeScript configuration in the `next.config.js` since Next.js 8.1.1 (we use a canary build) optionally configures it out of the box (we still need to explicitly list the typescript dependencies in `package.json`).
=> Simplified next.config.js as Next.js 8.1.1+ has built-in support for TypeScript

backend/migrations/20190725-01-migrate-timestamps-and-heights-to-bigint.js, backend/models/Block.js, backend/models/Node.js, backend/src/index.js, frontend/components/Block.js, frontend/components/blocks/BlocksRow.js, frontend/components/dashboard/DashboardBlocksBlock.js, frontend/components/dashboard/transaction/transaction.js, frontend/components/transactions/TransactionsRow.js
@robin-thomas FYI, I have changed the internal storage for timestamps (`blocks.timestamp` and `nodes.last_seen`) to save data as [UNIX epoch] milliseconds, and it is now a number type instead of a string.
=> Migrated timestamps type into BIGINT (milliseconds) instead of strings

backend/src/near.js, backend/src/sync.js, backend/src/wamp.js
/cc @robin-thomas 
We can now query Nearcore from frontend via WAMP:
```js
await call(".nearcore-query", ["account/register.near", ""])
```
=> Exposed (proxy) Nearcore query API via backend (#53)

frontend/pages/api/nodes.js
*Resolve #76*
This way we avoid logging load-balancer IP addresses instead of real ones.
=> Use x-forwarded-for as a source of node IP address

frontend/src/components/dashboard/DashboardTransactions.jsx, frontend/src/components/transactions/ActionsList.tsx, frontend/src/components/transactions/Transactions.tsx, frontend/src/components/transactions/TransactionsList.tsx, frontend/src/components/transactions/__tests__/ActionsList.test.tsx, frontend/src/components/transactions/__tests__/TransactionsList.test.tsx, frontend/src/components/transactions/__tests__/__snapshots__/ActionsList.test.tsx.snap, frontend/src/components/transactions/__tests__/__snapshots__/TransactionsList.test.tsx.snap, frontend/src/components/transactions/__tests__/common.tsx, frontend/src/libraries/explorer-wamp/transactions.ts, frontend/src/pages/accounts/[id].jsx, frontend/src/pages/transactions/index.jsx
I have assumed that `Array.reverse()` was not in-place (which turned out to be a wrong assumption). I have initially started with a simple fix changing `actions.reverse()` to `[...actions].reverse()`, but then I wanted to avoid shallow copies of the arrays and decided to reverse the components instead of the input arrays.
Another item that is fixed now is the order of actions on the Transaction Details page (they used to be in a reverse order, which does not make a lot of sense from the user perspective), and the order of transactions/actions on the Block Details page (the same reasoning).
=> Fixed actions ordering

.gitignore, backend/src/wamp.js, frontend/src/components/transactions/ReceiptRow.tsx, frontend/src/components/transactions/ReceiptsList.tsx, frontend/src/components/transactions/TransactionDetails.tsx, frontend/src/components/transactions/__tests__/ReceiptRow.test.tsx, frontend/src/components/transactions/__tests__/ReceiptsList.test.tsx, frontend/src/components/transactions/__tests__/TransactionDetails.test.tsx, frontend/src/components/transactions/__tests__/__snapshots__/ReceiptRow.test.tsx.snap, frontend/src/components/transactions/__tests__/__snapshots__/ReceiptsList.test.tsx.snap, frontend/src/components/transactions/__tests__/__snapshots__/TransactionDetails.test.tsx.snap, frontend/src/components/transactions/__tests__/common.tsx, frontend/src/libraries/explorer-wamp/transactions.ts, frontend/src/pages/transactions/[hash].jsx
*Resolves #91*
Notes:
1. Transaction fees are not currently exposed via RPC, so we cannot show them yet. https://github.com/nearprotocol/nearcore/issues/1299
2. ~Action result and logs are not implemented yet, this is the only item left to be implemented.~
3. Mobile is ok, but we should definitely get back to it one day to review mobile readiness (including performance and network traffic size optimization) #111 
4. ~Tests are coming~
5. Links to the transaction details page from the dashboard, list of transactions, block details, account details pages work fine (in fact, those pages reuse the same component, so it was just a change in a single place)
6. Render.com deployment won't work for this PR as it introduces a change on the proxy-backend.
~Here is an example of a direct link to a …
=> Implemented Transaction Details Page

frontend/src/components/utils/DataProvider.tsx, frontend/src/libraries/config.ts, frontend/src/libraries/explorer-wamp/index.ts, frontend/src/pages/_app.jsx
It was a multi-network compatibility issue. The domain names of the render.com deployments (e.g. `near-explorer-frontend-pr-133.onrender.com`) do not match any of the networks. The fix just falls back any unknown domain to the first configured network.
=> Fixed PRs deployment on render.com

backend/src/sync.js
NOTE: We should query this information on the frontend from the node on demand.
=> fix: Hotfixing a broken Explorer due to the huge args to FunctionCall which we tried to save to the DB

frontend/next-env.d.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/transactions/ActionMessage.tsx, frontend/src/components/transactions/__tests__/__snapshots__/ActionMessage.test.tsx.snap, frontend/src/components/transactions/__tests__/__snapshots__/ActionRow.test.tsx.snap, frontend/src/components/transactions/__tests__/__snapshots__/ActionsList.test.tsx.snap, frontend/src/components/utils/CodePreview.tsx, frontend/src/libraries/explorer-wamp/transactions.ts
*Resolves #181*
The unit-tests are updated and no extra coverage is required at the moment.
I want to push these changes ASAP to resolve the broken Explorer state.
P.S. `hexdump-nodejs` (suggested by Vlad Grichina) did not play well with ES6 imports.
=> fix: Added hex view for the contract arguments

frontend/src/components/transactions/ActionMessage.tsx, frontend/src/components/transactions/__tests__/__snapshots__/ActionMessage.test.tsx.snap, frontend/src/components/transactions/__tests__/__snapshots__/ActionRow.test.tsx.snap, frontend/src/components/transactions/__tests__/__snapshots__/ActionsList.test.tsx.snap, frontend/src/components/utils/CodePreview.tsx
> Warning: Use the `defaultValue` or `value` props instead of setting children on <textarea>.
=> fix(frontend): Fixed React warning about textarea usage

backend/src/config.js, backend/src/sync.js, backend/src/utils.js
"Fortunately", JS is fine comparing `12 < "13"` and somehow giving `true`, so the config options were respected if they were valid numbers.
I have also fixed a one-off check for the configuration options leading to one more extra item allowance over the limit.
Added some delay between chunks fetching retries.
=> fix: Backend should parse some environment variables (config values) as integers

frontend/src/components/accounts/AccountDetails.tsx, frontend/src/components/accounts/__tests__/__snapshots__/AccountDetails.test.tsx.snap
As per the switch from State renting to State staking, `storage_paid_at` is no longer useful. Thus, removing it from the UI. https://github.com/nearprotocol/nearcore/issues/2271
No extra tests are needed.
=> feature: Removed the deprecated storage_paid_at field

backend/models/Transaction.js
Thanks @icerove for catching this out!
This improved the queries' performance even further (for obvious reasons...)
=> feat(backend): Added an index on transactions.block_timestamp

backend/models/Account.js, backend/package.json, backend/src/index.js, backend/src/sync.js, backend/src/wamp.js, frontend/src/components/accounts/AccountDetails.tsx, frontend/src/components/accounts/AccountRow.tsx, frontend/src/components/accounts/__tests__/AccountDetails.test.tsx, frontend/src/components/utils/autoRefreshHandler.tsx, frontend/src/libraries/explorer-wamp/accounts.ts, frontend/src/pages/accounts/[id].jsx
fix #185 
backend:
1. generate nearcore-EXPERIMENTAL_genesis_records and nearcore-EXPERIMENTAL_genesis_config methods in the src/wamp.js since RPC has this and may use in the future.
2. generate saveGenesis method to insert records into data base. Generate syncGenesisState method in the src/sync.js and expose it in the src/index.js. Do not regular fetch genesis for an hour since it will occur unique error and not insert again at all. other are the same as regularSyncNewNearcoreState.
3. add accountIndex field to make it possible to scroll accounts from genesis. add indexes as transaction table to query 15 accounts.
frontend:
1. delete getAccountBasic function since hash and timestamp from genesis will not be null. Fix getAccountInfo to fetch all necessary account information same time. …
=> fix frontend and add indexes to account

backend/src/wamp.js
*Resolves #276*
The root cause of the issue was not the empty account ID, but the missing signature.
=> fix(backend): Show nodes that did not sign the telemetry data (non-validation nodes)

frontend/src/pages/_app.jsx
I noticed that H1s tend to overflow the page/screen on mobile devices. I’ve added a dynamic font size (for all H1s) based on screen width (min 28px, max 48px), and word-wrap for longer account IDs.
=> fix overflowing H1s

.github/workflows/continuous-integration-workflow.yml
Currently, CI does not work for our external contributors: https://github.com/near/near-explorer/pull/335
Docs on Github Actions: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
=> refactor: Enabled CI jobs to be run on Pull Requests, so external contributions are also checked

backend/models/Transaction.js, backend/src/sync.js, frontend/src/components/transactions/Transactions.tsx, frontend/src/components/transactions/__tests__/common.tsx, frontend/src/components/utils/autoRefreshHandler.tsx, frontend/src/libraries/explorer-wamp/transactions.ts
the transaction query failure is from all the transactions have same block_timestamp which we use to indicate the pagination In the future, this maybe more easily to happen and I suggest just like what we do to accounts table, add one more index column and query both
=> fix: Fixed pagination of transactions in a single block

backend/models/Block.js, backend/package-lock.json, backend/src/sync.js
It is follow up of the discussion in https://github.com/near/near-explorer/issues/365
Testing Plan
============
Manually checked all the references and ensured that we don't use
gas_limit and gas_used anywhere both in the backend and the frontend.
=> refactor(backend): Removed deprecated Block header fields (gas_limit and gas_used)

frontend/src/components/contracts/ContractDetails.tsx
This is a quite techy explanation, so feel free to suggest a better one
=> fix(frontend): Clarified the documentation message for the locked state of a contract

backend/src/config.js, backend/src/sync.js
This was the root cause of recent Explorer lagging behind the tip of the chain.
=> fix(backend): Limited the number of new blocks synced in a single iteration to prevent lagging behind

backend/src/wamp.js
I noticed in the logs that some IPs could not be resolved via our geoIP database which prevented the Telemetry information being stored into the database (it was just crashing there for one of the validators)
=> fix(backend): handle missing geoIP information gracefully

frontend/next.config.js, frontend/src/__mocks__/next/config.js
It is unknown to me how our tests pass without this fix :fearful: 
Unit tests suddenly started crashing on my end with quite a cryptic message:
```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: Cannot read property 'name' of undefined".] {
code: 'ERR_UNHANDLED_REJECTION'
}
```
=> fix(frontend): Fixed the next.js config mock for unit tests

backend/src/wamp.js
Trying to open `lockup.near` account on mainnet it was reported as missing due to an internal error (it tried and failed to do some lockup contract method calls)
=> fix(backend): Fixed a crash on getting balance of a lockup account

frontend/src/components/dashboard/DashboardHeader.tsx
Auto-capitalization messes with ability to type account name like `bananaswap.near` easily
=> Make search field less annoying on mobile

frontend/src/pages/api/circulating-supply-in-near.js, frontend/src/pages/api/circulating-supply.js
=> feat(frontend): Exposed a simple API to query circulating supply estimate in whole NEAR

CONTRIBUTING.md, frontend/src/components/accounts/AccountDetails.tsx, frontend/src/components/blocks/BlockDetails.tsx, frontend/src/components/contracts/ContractDetails.tsx, frontend/src/components/dashboard/DashboardBlock.tsx
docs.near.org has relocated some information... this PR updated those links 🙂
=> update docs links

backend/src/db-utils.js, backend/src/stats.js, frontend/src/components/stats/ActiveAccountsList.tsx, frontend/src/components/stats/ActiveContractsList.tsx, frontend/src/pages/stats/index.jsx
Resolves #528 and additionally address the transactions count history chart (removed the current date from the list which was a rounding bug)
=> fix(stats): Fixed various issues with the existing charts

frontend/src/components/dashboard/DashboardBlock.tsx
The average block time is an inversion of the block production speed. I failed here during the refactoring.
=> fix(frontend): Fixed the average block time

frontend/src/components/stats/ActiveAccountsByDate.tsx, frontend/src/components/stats/ActiveAccountsList.tsx, frontend/src/components/stats/ActiveContractsByDate.tsx, frontend/src/components/stats/ActiveContractsList.tsx
users are confused what is active status from our side. I just add `in last 14 days` in title, if you have better ideas, please touch it.
=> feat(frontend): update titles on charts and stats page to reflect the timeframe

frontend/src/components/transactions/ReceiptRow.tsx, frontend/src/components/transactions/__tests__/__snapshots__/ReceiptRow.test.tsx.snap
Ideally, we want to display a block height instead of a block hash since it is more useful for the end-user, but we can improve that in #589.
Example page: https://near-explorer-frontend-with-indexer-pr-5jya.onrender.com/transactions/BnQcHwyvP9EfdaLEErA8CsL2yVVNGs3Lfds8o4MMPPDL
=> feat(frontend): Added a block id to the receipt details on Transaction Details page

backend/src/db-utils.js, backend/src/wamp.js
since this query is already move to other repo and bridge query that not related to explorer will not put in explorer backend, delete bridge query part
=> backend: delete unused bridge query 

frontend/src/libraries/explorer-wamp/transactions.ts
This partially resolves #628.
Before:
```
mainnet_explorer=> EXPLAIN ANALYZE SELECT
transactions.transaction_hash as hash,
transactions.signer_account_id as signer_id,
transactions.receiver_account_id as receiver_id,
transactions.included_in_block_hash as block_hash,
DIV(transactions.block_timestamp, 1000*1000) as block_timestamp,
transactions.index_in_chunk as transaction_index
FROM transactions WHERE transaction_hash IN (SELECT DISTINCT originated_from_transaction_hash FROM receipts WHERE receipts.predecessor_account_id = 'near' OR receipts.receiver_account_id = 'near') ORDER BY transactions.block_timestamp DESC, transactions.index_in_chunk DESC
LIMIT 10;
QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------- …
```
=> feat(frontend): improved transactions list query performance

frontend/src/components/nodes/Validators.tsx, frontend/src/context/NodeProvider.tsx
=> feat(frontend): display up to 120 nodes per page

backend/package-lock.json, backend/package.json, backend/src/aggregations.js, backend/src/index.js, frontend/src/components/nodes/ValidatorRow.tsx
=> fix: display N/A fees and delegators count for non-staking-pools on the Nodes page

frontend/src/components/stats/GasUsedByDate.tsx, frontend/src/context/DatabaseProvider.tsx
=> fix(frontend): fixed a missing gas fee chart

frontend/src/pages/api/circulating-supply-in-near.js, frontend/src/pages/api/circulating-supply.js
still investigate why we don't have host parameter in request here https://explorer.near.org/api/circulating-supply
=> fix: take hostname from req.headers.host

frontend/package-lock.json, frontend/package.json, frontend/src/components/utils/LangSwitcher.tsx, frontend/src/libraries/language.js, frontend/src/pages/_app.jsx
With https://github.com/near/near-explorer/pull/679, now we support i18n in explorer. 
However, server side rendering is in a mess.
This fix will render i18n in SSR with either default language or user selected langauge.
=> Fix i18n error in SSR

frontend/src/pages/blocks/[hash].jsx
With https://github.com/near/near-explorer/pull/679, now we support i18n in explorer. 
Here we missed one translation here for **Receipts** in block page: https://explorer.testnet.near.org/blocks/C4qtSqRyfQpH6amDMWgfqpXExhnk76G5VSVNLRC5G3ku
=> Fix i18n of block page

frontend/src/libraries/language.js
Fixes: #688
`moment`'s locale is inconsistent with the browser locale.
Ensure `moment.updateLocale()` is called before `moment.locale()`
=> fix(frontend): Fix inconsistent `moment` locale with browser locale

frontend/src/components/accounts/AccountDetails.tsx, frontend/src/components/blocks/BlockDetails.tsx, frontend/src/components/contracts/ContractDetails.tsx, frontend/src/components/nodes/NodesEpoch.tsx, frontend/src/components/nodes/__test__/__snapshots__/NodesEpoch.test.tsx.snap, frontend/src/components/stats/ProtocolConfigInfo.tsx, frontend/src/components/transactions/TransactionDetails.tsx, frontend/src/translations/en.global.json, frontend/src/translations/zh-hans.global.json
Fix the below issues: 
=>
**"收据"** => **"交易回执"**
=>
=> feat(frontend): fix several Chinese translation issues

frontend/src/components/nodes/ValidatorRow.tsx, frontend/src/translations/en.global.json, frontend/src/translations/vi.global.json, frontend/src/translations/zh-hans.global.json
Fix: the missing i18n support in the ValidatorRow component
Related PR: #700 
Because I don’t understand Vietnamese, it kept the default in Vietnamese mode
=> fix(frontend): the missing i18n support in the ValidatorRow component

.github/workflows/fossa.yml
Running FOSSA only on master is sufficient enough. We can easily revert or fix the issues as they occur.
=> feat(fossa): run fossa only on master to unbreak external contributors

frontend/src/components/transactions/ReceiptRow.tsx, frontend/src/components/transactions/__tests__/ReceiptRow.test.tsx, frontend/src/components/transactions/__tests__/__snapshots__/ReceiptRow.test.tsx.snap, frontend/src/components/utils/BlockLink.tsx, frontend/src/components/utils/ReceiptLink.tsx, frontend/src/pages/transactions/[hash].jsx
Those fields like `receipt_id`, `predecessor_id` and `receiver_id` are links to Receipt and AccountPage accordingly
=> fix(frontend): Add links to useful fields in receipts section

frontend/src/libraries/explorer-wamp/accounts.ts, frontend/src/libraries/explorer-wamp/transactions.ts, frontend/src/pages/accounts/[id].jsx, frontend/src/pages/blocks/[hash].jsx, frontend/src/pages/transactions/[hash].jsx, frontend/src/translations/en.global.json, frontend/src/translations/vi.global.json, frontend/src/translations/zh-hans.global.json
User tries to view transaction (already created and redirected from wallet). But the page shows default values that doesn't make any sense and get user a bit confused. This can happen by a lot of receipts which must proсessed by validators. That's why that kind of transactions will be available in rpc in some time.
Solution: show to the user correct message that transaction which will be available soon.
Also we had such a problem with accounts when we try to query to a non-existent account. For now we will show the message that account does not exist
=> refactor(frontend): Display correct error message on pages without any data

backend/src/stats.js, frontend/src/components/stats/NewContractsByDate.tsx
There is still a bug on the analytics side. I created the hotfix for this chart, but I need to investigate it on analytics side more.
=> Move cumulative logic to frontend side for unique contracts

backend/src/db-utils.js, frontend/src/components/stats/CirculatingSupplyStats.tsx, frontend/src/components/stats/ProtocolConfigInfo.tsx, frontend/src/pages/stats/index.jsx
Resolves #750 
We will show this chart only for `mainnet`:
=> fix(frontend): Fix values on circulating supply chart

backend/src/accounts.js, backend/src/blocks.js, backend/src/chunks.js, backend/src/contracts.js, backend/src/db-utils.js, backend/src/receipts.js, backend/src/transactions.js, backend/src/wamp.js, frontend/src/components/accounts/AccountDetails.tsx, frontend/src/components/blocks/BlockDetails.tsx, frontend/src/components/blocks/Blocks.tsx, frontend/src/components/blocks/BlocksRow.tsx, frontend/src/components/blocks/__tests__/BlockDetails.test.tsx, frontend/src/components/contracts/ContractDetails.tsx, frontend/src/components/transactions/Transactions.tsx, frontend/src/components/utils/Search.jsx, frontend/src/context/NetworkStatsProvider.tsx, frontend/src/libraries/explorer-wamp/accounts.ts, frontend/src/libraries/explorer-wamp/blocks.ts, frontend/src/libraries/explorer-wamp/contracts.ts, frontend/src/libraries/explorer-wamp/receipts.ts, frontend/src/libraries/explorer-wamp/transactions.ts, frontend/src/pages/accounts/[id].jsx, frontend/src/pages/blocks/[hash].jsx
_Resolves_ #773 
We had a mess with queries as some of them was on backend but huge amount of them on frontend
=> refactor: Move queries to backend

backend/src/db-utils.js
After refactoring queries I miss this chart:
=> fix(backend): Fix 'Top 10 active accounts for 2 weeks' chart

backend/src/db-utils.js, backend/src/index.js, frontend/src/libraries/explorer-wamp/accounts.ts
_Resolves_: #780 
Also, I find a bug with number of transactions on AccountDetails page. If account was just created, there was no any transactions at the top of page, but you could see all of them in the **Transactions** section.
=> fix(backend): Fix viewing of deleted account

backend/src/wamp.js
We saw people abusing it sending heavy requests and slowing our Explorer experience down, so it is a natural next step after #774
If you want to make queries, use the public shared access or run your own indexer: https://github.com/near/near-indexer-for-explorer/#shared-public-access
=> feat(backend): sunset `select:INDEXER_BACKEND` endpoint

backend/src/db-utils.js
Resolves #786 
From now we convert date to timestamp via js only. I've checked income and outcome transactions count on `near` account and values are same but loads faster
=> refactor(backend): Refactor queries for income and outcome tx count

backend/src/wamp.js
Since new deploy of testnet we haven't `storage_amount_per_byte` property in `EXPERIMENTAL_genesis_config` query, so we change the query with `EXPERIMENTAL_protocol_config`
=> fix(backend): Switch `EXPERIMENTAL_genesis_config` query with valid one

backend/src/db-utils.js
Previously we had a very hard query for `14 Day History` transactions chart (especially for `mainnet`). That's why we rewrite this query to use `near-analytics`
=> refactor(backend): Rewrite query of `14 day history` chart

frontend/README.md
Apparently, it should be `mainnet` in NOTE.
=> docs: Fix README.md typo

backend/src/db-utils.js, backend/src/transactions.js, frontend/README.md, frontend/package-lock.json, frontend/src/components/transactions/TransactionAction.tsx, frontend/src/libraries/explorer-wamp/accounts.ts, frontend/src/libraries/explorer-wamp/blocks.ts, frontend/src/libraries/explorer-wamp/receipts.ts, frontend/src/libraries/explorer-wamp/transactions.ts
After we moved our queries from frontend to backend we got a lot of `console.error` that was displayed on every failed request even when we control it. I've changed the structure of our errors messages for better understanding of what goes wrong.
Also I've find a cause why pagination on Blocks page was broken and fixed it as well
=> refactor(frontend&backend): Display `console.error` whenever it needed

backend/README.md, backend/config/database.js, backend/config/env-indexer-mainnet, backend/config/env-indexer-testnet, backend/models/index.js, backend/package.json, backend/src/config.js, backend/src/index.js, backend/src/near.js
@shelegdmitriy @luixo I don't expect you do extensive review here, but I still want to mention you in the PR, so you are aware of the change
Main objectives:
* I wanted to add a quick fix for telemetry database connection configuration, so it can use up to 15 connections (otherwise we cannot store 50+ telemetry requests per second of constant load)
* Along the way, I wanted to decouple read vs write credentials to telemetry database, so we can actually use the read replica for the read queries
* I decided to make the other configuration options more explicit as to what type of access they are going to be used (received a feedback from people that initially tried to use non-archival RPC server with Explorer and failed to fetch the details about transactions that were included more than 5 …
=> refactor(backend): disambiguated the configuration options

frontend/.babelrc, frontend/src/components/accounts/__tests__/__snapshots__/AccountDetails.test.js.snap, frontend/src/components/accounts/__tests__/__snapshots__/AccountRow.test.js.snap, frontend/src/components/blocks/__tests__/__snapshots__/BlockDetails.test.tsx.snap, frontend/src/components/blocks/__tests__/__snapshots__/BlocksRow.test.tsx.snap, frontend/src/components/nodes/__test__/__snapshots__/NodeRow.test.tsx.snap, frontend/src/components/nodes/__test__/__snapshots__/NodesEpoch.test.tsx.snap, frontend/src/components/nodes/__test__/__snapshots__/ValidatorRow.test.tsx.snap, frontend/src/components/nodes/__test__/__snapshots__/ValidatorsList.test.tsx.snap, frontend/src/components/transactions/__tests__/__snapshots__/ActionMessage.test.tsx.snap, frontend/src/components/transactions/__tests__/__snapshots__/ActionRow.test.tsx.snap, frontend/src/components/transactions/__tests__/__snapshots__/ActionsList.test.tsx.snap, frontend/src/components/transactions/__tests__/__snapshots__/ReceiptRow.test.tsx.snap, frontend/src/components/transactions/__tests__/__snapshots__/TransactionDetails.test.tsx.snap, frontend/src/components/utils/__tests__/__snapshots__/AccountLink.test.tsx.snap, frontend/src/components/utils/__tests__/__snapshots__/CardCell.test.tsx.snap, frontend/src/components/utils/__tests__/__snapshots__/ReceiptLink.test.tsx.snap, frontend/src/components/utils/__tests__/__snapshots__/Term.test.tsx.snap
Before we move to [rust compiler in jest](https://nextjs.org/docs/testing#setting-up-jest-with-the-rust-compiler), we need to turn on proper `style` tag snapshotting, which is not actually relevant at the moment (we snap class name hash instead of actual CSS content).
The option in `.babelrc` will be removed as soon as we'll enable next-generated `jest` config.
=> CSS in Jest tests

frontend/cypress/integration/account-details-navigation.spec.ts, frontend/src/pages/_app.tsx, frontend/src/pages/accounts/[id].tsx, frontend/src/pages/blocks/[hash].tsx, frontend/src/pages/transactions/[hash].tsx
[getInitialProps](https://nextjs.org/docs/api-reference/data-fetching/getInitialProps) are considered kinda deprecated, in favor for `getServerSideProps` and `getStaticProps`.
=> refactor(frontend): Switch to getServerSideProps

frontend/src/hooks/use-near-network.ts, frontend/src/pages/accounts/[id].tsx, frontend/src/pages/stats/index.tsx
It seems like absolute imports break `jest`, let's take them out as soon as it's possible :)
=> Refactor (frontend): no absolute imports

backend/README.md
The backend README says in its title that it is the frontend README.
Surely that was a typo.
=> backend: fix typo in readme

frontend/cypress/integration/dashboard-page.spec.ts, frontend/cypress/integration/nodes-page.spec.ts
A couple of cypress tests are failing everywhere, though those fails don't reproduce locally.
Let's skip them to unblock PRs and get back to them later (probably changing e2e library).
=> Fix: skip failing cypress tests

frontend/src/components/utils/ListHandler.tsx
Sometimes on Blocks page we could see `#undefined` instead of number of latest block
=> fix(frontend): Fix `undefined` in ListHandler on Blocks page

frontend/src/components/utils/ListHandler.tsx, frontend/src/libraries/explorer-wamp/blocks.ts
We had some strange behavior with forced loading blocks on Blocks page. When you click on "Refresh..." you'll see this:
Also we had some issue with block (hash: `CYug4KVfwXqt2cNhzzPDoN4Tz4EWEsrvj1hnna8tKrUk`). This block exist but we doun't display any information about it because `getGasUsedInBlock` request return null.
=> refactor(frontend): Fix forced loading of blocks

backend/src/db-utils.js
This PR just introduces method to execute 'executed receipts in block' to work on it in next PR
=> feat(backend): Introduce executed receipts in block method

frontend/next.config.ts
After `stitches` introduce we got first ESM module in out ecosystem, which broke `nextjs` build (but for some reason not on the first attempt).
The bug is that a ESM module uses `import` instead of `require` thus marked async and creates a circular dependency in imports. Problem is [known](https://github.com/vercel/next.js/issues/32360) though not addressed yet, but we got a solution - just turn off `esmExternals` experimental feature.
This problem reproduced on multiple commits locally starting from one with stitches (before verifying I cleaned up `node_modules`, `.next`, made clean install of packages and clean build.
Also, PR stages started to reproduce the problem.
For some reason (yet to discover) production is totally fine.
=> Fix: ESM module import

frontend/src/pages/accounts/[id].tsx, frontend/src/pages/blocks/[hash].tsx, frontend/src/pages/transactions/[hash].tsx
In production there is a mistake that gets us to 500 response.
It is caused if someone goes to `accounts/[id]` page, literally. In this case `[id]` doesn't match pattern but is literally `[id]` which make `params` props of `getServerSideProps` undefined.
=> Fix: Next.js params in special case

frontend/src/components/dashboard/DashboardNode.tsx
Dashboard [link to docs](https://docs.near.org/docs/validator/staking#run-the-node) seems to be outdated, so changed it to follow [here](https://docs.near.org/docs/develop/node/intro/what-is-a-node)
=> Fix (frontend): outdated dashboard link

render.yaml
In this PR:
- we upgrade plan for `frontend` service as it is not a docker image at the moment and required more RAM (will fix later);
- we downgrade plan for `wamp` service as it usually doesn't consume more than 2GB RAM and 1 CPU, if it does - something's wrong.
=> Feature: render.com plan change

backend/src/index.ts, frontend/src/components/nodes/ValidatorMainRow.tsx, frontend/src/components/nodes/ValidatorRow.tsx, frontend/src/components/nodes/ValidatorsList.tsx, frontend/src/components/nodes/__test__/validators.tsx, frontend/src/libraries/wamp/types.ts
I managed to reproduced the [problem](https://github.com/near/near-explorer/pull/906#issuecomment-1084742726) (kudos to @frol) and fixed it.
The bug was created by migration to typescript.
I decided to make types more semantical - and separate `stakingPoolInfo` to a nested object, removing the need to have types like `Foo | undefined | null`.
=> Fix: validators fee as null

backend/src/checks.ts, backend/src/config.ts, backend/src/index.ts, backend/src/near.ts
Addressing a problem of high CPU utilization of DB - I made a query to get pool ids way less frequent than before.
=> Bigger interval for pool ids check

backend/src/checks.ts, backend/src/index.ts, backend/src/procedure-handlers.ts, backend/src/pubsub.ts, frontend/src/components/dashboard/DashboardTransaction.tsx, frontend/src/components/dashboard/DashboardTransactionsHistoryChart.tsx, frontend/src/hooks/subscriptions.ts, frontend/src/types/procedures.ts, frontend/src/types/subscriptions.ts
@frol 
As a follow-up to out chat - I changed transaction history fetch from subscription to procedure call so we can do it just once and not rely on 10 minute refresh to render it.
=> Feature: transaction history as procedure

frontend.env, frontend/next.config.ts, frontend/src/__mocks__/next/config.ts, frontend/src/components/accounts/AccountDetails.tsx, frontend/src/components/utils/HeaderNetworkDropdown.tsx, frontend/src/context/NetworkContext.tsx, frontend/src/hooks/subscriptions.ts, frontend/src/hooks/use-fetcher.ts, frontend/src/hooks/use-network-context.ts, frontend/src/libraries/config.ts, frontend/src/libraries/transport.ts, frontend/src/libraries/wamp.ts, frontend/src/pages/_app.tsx, frontend/src/pages/accounts/[id].tsx, frontend/src/pages/api/circulating-supply-in-near.ts, frontend/src/pages/api/circulating-supply.ts, frontend/src/pages/api/fees-of-previous-7-days-utc.ts, frontend/src/pages/api/fees-of-previous-day-utc.ts, frontend/src/pages/api/metrics/indexer.ts, frontend/src/pages/api/nodes.ts, frontend/src/pages/api/status.ts, frontend/src/pages/blocks/[hash].tsx, frontend/src/pages/stats/index.tsx, frontend/src/pages/transactions/[hash].tsx, frontend/src/testing/utils.tsx, render.yaml
We currently have two networks passed around - the one from the list and another one extracted from it by the key.
Let's not repeat ourselves and keep the list and the key separate, calculating the data if needed.
=> Refactor: no duplicate network

backend/src/procedure-handlers.ts, backend/src/transactions.ts, common/src/types/procedures.ts, frontend/src/components/transactions/ReceiptRow.tsx, frontend/src/components/transactions/TransactionDetails.tsx, frontend/src/components/transactions/TransactionOutcome.tsx, frontend/src/components/transactions/__tests__/common.tsx, frontend/src/pages/transactions/[hash].tsx
It's quite hard to keep frontend server code simple with such a cumbersome calculations. It affects amount of data transferred on network as well.
I assume this code move may rise the stress on backend, we will be definitely able to see the effect after deployment.
=> Refactor: transaction calculations on server

backend/src/accounts.ts, backend/src/db-utils.ts, common/src/types/procedures.ts, frontend/src/components/accounts/AccountDetails.tsx, frontend/src/components/accounts/AccountRow.tsx, frontend/src/components/accounts/__tests__/AccountDetails.test.tsx
Extracting out the values helps keeping types consistent.
Also, addressing this issue: https://github.com/near/near-explorer/pull/992#discussion_r872571488
=> Refactor: created/deleted on account

frontend/src/components/dashboard/DashboardBlock.tsx, frontend/src/components/dashboard/DashboardNode.tsx, frontend/src/components/dashboard/DashboardTransaction.tsx, frontend/src/components/nodes/NodeNav.tsx, frontend/src/components/nodes/Validators.tsx, frontend/src/components/nodes/ValidatorsList.tsx, frontend/src/components/stats/ProtocolConfigInfo.tsx, frontend/src/hooks/data.ts, frontend/src/hooks/subscriptions.ts, frontend/src/pages/nodes/validators.tsx
In TRPC subscription result can be an error, so we probably need a way to show that.
Also, we can benefit from a proper `loading` state.
=> Feature: useSubscription object

backend/src/cron/index.ts, backend/src/cron/tasks.ts, backend/src/cron/types.ts
We'll need that not to fetch protocol config every second if epoch changes only once every 12 hours.
=> Feature: adjustable intervals

backend/src/cron/index.ts, backend/src/cron/tasks.ts, backend/src/database/queries.ts, backend/src/global-state.ts, backend/src/providers/network.ts, backend/src/providers/stats.ts, backend/src/router/procedures.ts, backend/src/router/subscriptions.ts, backend/src/router/types.ts, backend/src/types.ts, frontend/src/components/stats/ProtocolConfigInfo.tsx
It seems like we can fetch genesis details just once and propagate them later.
=> Refactor: genesis config subscription

backend/src/config.ts, common/src/types/common.ts, frontend/next.config.ts, frontend/src/__mocks__/next/config.ts, frontend/src/components/utils/HeaderNetworkDropdown.tsx, frontend/src/testing/utils.tsx
I researched through other NEAR projects and found out nobody uses `localhostnet` except us but `localnet`.
This is the rename.
=> Fix: localhostnet -> localnet

backend/src/router/subscriptions.ts, common/src/index.ts, common/src/utils/queries.ts, frontend/src/pages/_app.tsx
I found a bug: whenever our subscription cached is not filled yet - we pass undefined to the client as the value which leads to an error on the page.
=> Fix: subscription error on no prefetched data

common/src/types/rpc.ts, frontend/src/components/transactions/__tests__/common.tsx
I decided to expand `Failure` param of `ExecutionStatusView` type and I use this [doc](https://docs.rs/near-primitives/0.12.0/near_primitives/errors/enum.TxExecutionError.html). I need this type [here](https://github.com/near/near-explorer/blob/54bdd2a940a2eebd875e577d01277f0175fbaeb0/frontend/src/components/beta/transactions/ReceiptDetails.tsx#L78) in this [PR](https://github.com/near/near-explorer/pull/977).
=> Refactor: Extend receipt execution outcome type

backend/src/database/queries.ts, backend/src/router/types.ts, backend/src/utils/bigint.ts, common/src/index.ts, common/src/types/procedures.ts, common/src/utils/near.ts, frontend/src/components/dashboard/DashboardTransaction.tsx, frontend/src/components/dashboard/DashboardTransactionsHistoryChart.tsx, frontend/src/components/stats/CirculatingSupplyStats.tsx, frontend/src/components/stats/TransactionsByDate.tsx, frontend/src/libraries/bigint.ts, frontend/src/translations/en/common.json, frontend/src/translations/ru/common.json, frontend/src/translations/ua/common.json, frontend/src/translations/vi/common.json, frontend/src/translations/zh-hans/common.json
What's that about?
- sending less prop names over the wire in big (500+ items) arrays
- calculating bigints of those arrays once every hour on backend side rather than on frontend side on every render
- factoring out `getOption`s functions not to recreate them on every render
- leveraging `time` type of echarts
- spinners on proper places of loading charts
=> Refactor: charts refactor

common/src/types/procedures.ts, frontend/src/components/beta/transactions/TransactionHeader.tsx, frontend/src/components/beta/transactions/TransactionStatus.tsx, frontend/src/components/transactions/TransactionDetails.tsx, frontend/src/components/transactions/TransactionExecutionStatus.tsx, frontend/src/components/transactions/__tests__/common.tsx, frontend/src/pages/beta/transactions/[hash].tsx
Part of transaction router refactor: https://github.com/near/near-explorer/pull/1065
Renaming `Transaction` to remove confusion
=> Refactor: rename old transaction

frontend/src/components/utils/Timer.tsx, frontend/src/hooks/use-format-distance.ts
I decided to improve `useFormatDistanceToNow` hook and now it can calculate interval to a given timestamp. That’s because I need this in this PR #1048
=> Refactor: Introduce useFormatDistance hook

backend/src/config.ts, backend/src/database/databases.ts, backend/src/database/models/readOnlyIndexerActivity/balance-changes.ts, backend/src/database/models/readOnlyIndexerActivity/index.ts, backend/src/router/account/activity.ts, backend/src/router/account/index.ts, backend/src/router/validators.ts, common/src/types/procedures.ts, frontend/src/components/beta/accounts/AccountActivityBadge.tsx, frontend/src/components/beta/accounts/AccountActivityView.tsx, frontend/src/components/beta/accounts/AccountTabs.tsx, frontend/src/components/beta/common/CopyToClipboard.tsx, frontend/src/hooks/use-account-page-options.ts, frontend/src/pages/beta/accounts/[...slug].tsx, frontend/src/translations/en/common.json, frontend/src/translations/ru/common.json, frontend/src/translations/ua/common.json, frontend/src/translations/vi/common.json, frontend/src/translations/zh-hans/common.json, frontend/src/translations/zh-hant/common.json, patches/kanel+2.4.4.patch
This is a version of #937 with more context added to each record.
Preview links:
https://frontend-pr-1006-3r1e.onrender.com/beta/accounts/multisender.app.near
https://frontend-pr-1006-3r1e.onrender.com/beta/accounts/qbit.poolv1.near
https://frontend-pr-1006-3r1e.onrender.com/beta/accounts/9755042d33e148f87265c3343b69ed902939f166.lockup.near
https://frontend-pr-1006-3r1e.onrender.com/beta/accounts/foundation.near
https://frontend-pr-1006-3r1e.onrender.com/beta/accounts/82f09db4a072c66f89e8e226234181bb53f5ec24.lockup.near
=> Feature: beta account activity

backend/src/router/transaction/get.ts, common/src/types/procedures.ts, frontend/package.json, frontend/public/static/images/icon-arrow-down-black.svg, frontend/src/components/beta/common/AccountLink.tsx, frontend/src/components/beta/common/BlockLink.tsx, frontend/src/components/beta/common/CodeArgs.tsx, frontend/src/components/beta/common/JsonView.tsx, frontend/src/components/beta/common/UtcLabel.tsx, frontend/src/components/beta/transactions/InspectReceipt.tsx, frontend/src/components/beta/transactions/ReceiptDetails.tsx, frontend/src/components/beta/transactions/ReceiptInfo.tsx, frontend/src/components/beta/transactions/ReceiptKind.tsx, frontend/src/components/beta/transactions/TransactionActionsList.tsx, frontend/src/components/beta/transactions/TransactionReceipt.tsx, frontend/src/pages/beta/transactions/[hash].tsx, frontend/src/translations/en/common.json, frontend/src/translations/ru/common.json, frontend/src/translations/ua/common.json, frontend/src/translations/vi/common.json, frontend/src/translations/zh-hans/common.json, frontend/src/translations/zh-hant/common.json, package-lock.json
Here is the second part of beta TransactionDetails page. This PR includes view of details (receipts and data).
- https://frontend-pr-1048-m877.onrender.com/beta/transactions/EztXEUwan7o5vYUZsqNtvdg7tymNwCnKMcTr97q2MiMt;
- https://frontend-pr-1048-m877.onrender.com/beta/transactions/3xixQuPmEn1vpnbwaNHhEjEGFUHy3CWSLJx7rAuvjNZp;
Here is a previous [PR](https://github.com/near/near-explorer/pull/977) just for reference.
=> Feature: beta transaction details view

frontend/src/translations/vi/common.json
Due to the change in the PR: https://github.com/near/near-explorer/pull/1070/files#diff-66205e01d9991ccf3505fa0f9f55c265bc8d8dd63f2cc43a3744e13c3238754a, the translation of transaction status `success` is wrong for Vietnamese, which has been misleading Vietnamese users because all successful transactions are now `failure`. 
To avoid such issue in the long run, for critical and impactful update to the translation JSON files, it would be recommended to request review from at least one contributor who knows well about the language. 
We can create a file (e.g. `translation.md`) that tracks the translators / owners for each language if needed.
```md
en: @alice
ru: @bob
zh-Hans: @charlie
vi: @dave
```
=> fix: Vietnamese translation of transaction status `success`

backend/src/router/receipt/get-transaction-hash.ts, backend/src/router/receipt/index.ts, frontend/src/pages/receipts/[id].tsx
Adding an ability to fetch page `https://explorer.near.org/receipts/<receipt_id>/` and get redirected to `https://explorer.near.org/transactions/<transaction_hash>#<receipt_id>/`.
=> Feature: receipt redirect page

backend/src/database/models/readOnlyTelemetry/nodes.ts, backend/src/router/telemetry.ts, backend/src/router/validators.ts, backend/src/utils/telemetry.ts
`block_production_tracking_delay` and similar fields are already populated by nodes in testnet, but not yet in mainnet.
The PR is not tested, please advise how to test it.
=> Store all fields from TelemetryInfo in the telemetry DB

frontend/src/translations/zh-hans/common.json, frontend/src/translations/zh-hant/common.json
Fixes: #1118
With this fix, the Chinese data format will be `2022年12月3日, 下午6:27:45`
=> fix: Chinese date time format

frontend/package.json, frontend/src/components/beta/accounts/AccountActivityView.tsx, frontend/src/components/beta/common/AccountLink.tsx, frontend/src/components/utils/BetaSwitch.tsx, frontend/src/components/utils/Header.tsx, frontend/src/components/utils/MobileHeaderNavDropdown.tsx, frontend/src/components/utils/Switch.tsx, frontend/src/hooks/use-account-page-options.ts, frontend/src/hooks/use-beta-options.ts, frontend/src/hooks/use-beta.ts, frontend/src/hooks/use-watch-beta.ts, frontend/src/libraries/beta.ts, frontend/src/libraries/styles.ts, frontend/src/pages/_app.tsx, frontend/src/pages/accounts/[...slug].tsx, frontend/src/pages/beta/transactions/[hash].tsx, frontend/src/pages/transactions/[hash].tsx, package-lock.json
What we do here is we get rid of `/beta` prefix as the main way to get into beta pages and introduce a cookie to keep the data about `beta` preferences.
Currently, you can add `?beta=anything` to turn on the beta switch (which is hidden by default) and you'll be able to opt-in/out for `beta` pages.
=> Feature: unify beta pages representation

frontend/src/components/nodes/ValidatorProgressElement.tsx
Uptime counting has used only produced/expected blocks ratio. It's a bug for chunk-only producers uptime indicating.
| Current problem  | Fixed problem  |
| ------------------| -------------- |
| <img width="500" src="https://user-images.githubusercontent.com/74172766/209623684-6a17a0a5-5bc4-4454-b186-b26f30c17b82.png">   | <img width="500" src="https://user-images.githubusercontent.com/74172766/209623799-b963258b-364b-473d-83a0-b63f586613a9.png">       |
=> Fix: counting uptime for chunk-only producers

backend/src/router/transaction/get.ts, frontend/src/components/transactions/ReceiptRow.tsx, frontend/src/components/transactions/TransactionDetails.tsx
RPC doesn't respond the full tree of receipts for [some transactions](https://github.com/near/nearcore/issues/8321).
Until it is fixed we should at least show partial transaction.
I added a block with `Receipt <id> not found` stub.
Fixes https://github.com/near/near-explorer/issues/1136
=> Fix: empty receipts

frontend/src/context/LanguageContext.tsx, frontend/src/hooks/use-date-format.ts, frontend/src/hooks/use-date-locale.ts, frontend/src/hooks/use-format-distance.ts, frontend/src/libraries/date-locale.ts, frontend/src/pages/_app.tsx, frontend/src/testing/env.ts, frontend/src/testing/utils.tsx
This is a step towards identical server-side and client-side rendering of dates.
I hope [there will be an easy way](https://github.com/vercel/next.js/discussions/46032) to implement it.
=> Refactor: cache locale

frontend/src/components/nodes/ValidatorMainRow.tsx, frontend/src/components/nodes/ValidatorMetadataRow.tsx, frontend/src/components/utils/Content.tsx, frontend/src/pages/_app.tsx
React 18 makes defining `children` strict in props.
=> Refactor: PropsWithChildren

frontend/src/components/utils/ServiceStatus.tsx, frontend/src/components/utils/ToastController.tsx
We don't actually use original `react-hot-toast` styles, so we don't need headed version.
=> Refactor: headless react-hot-toast

backend/src/router/account/balance.ts, backend/src/router/account/by-id.ts, backend/src/router/account/index.ts, backend/src/router/account/list.ts, frontend/src/components/accounts/AccountRow.tsx, frontend/src/components/accounts/Accounts.tsx, frontend/src/components/accounts/__tests__/AccountRow.test.tsx, frontend/src/components/accounts/__tests__/__snapshots__/AccountRow.test.tsx.snap
Currently we load `accounts.byIdOld` for every account in account list though only one field is needed there.
This refactor lessen the amount of data going around on the backend.
=> Refactor: balance in account row
